name: Frontend CI/CD - Innovatech

on:
  push:
    branches:
      - deploy # Trigger basado en la rama exigida por la pauta

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      # Manejo adecuado y seguro de credenciales (Mapeado a GitHub Secrets)
      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Construcción de la imagen basada en el Dockerfile multi-stage optimizado
      - name: Construir y Subir Imagen Docker
        uses: docker/build-push-action@v4
        with:
          context: ./FrontendInnovatech
          file: ./FrontendInnovatech/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend-innovatech:latest

  deploy-to-ec2:
      needs: build-and-push
      runs-on: ubuntu-latest
      steps:
        - name: Desplegar en AWS Academy EC2 mediante Docker Compose
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.AWS_EC2_HOST }}
            username: ec2-user
            key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
            script: |
              cd /home/ec2-user/innovatech-stack || mkdir -p /home/ec2-user/innovatech-stack && cd /home/ec2-user/innovatech-stack
              echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" > .env
              
              docker compose pull frontend-innovatech
              docker compose up -d frontend-innovatech
              
              docker image prune -f